tasks/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import TaskList,MyTask,AllTask,CreateTask,ViewTask,UpdateTask,DeleteTask
from django.contrib.auth.decorators import login_required

app_name='tasks'

urlpatterns = [
    path('',login_required(TaskList.as_view()),name='task_list'),
    path('my_task/',login_required(MyTask.as_view()), name='my_task'),
    path('all_task/',login_required(AllTask.as_view()),name='all_task'),
    path('create_task/<str:id>',login_required(CreateTask.as_view()),name="create_task"),
    path('view_task/<str:id>',login_required(ViewTask.as_view()),name="view_task"),
    path('update_task/<str:id>',login_required(UpdateTask.as_view()),name="update_task"),
    path('delete_task/<str:id>',login_required(DeleteTask.as_view()),name="delete_task"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from api.router import router
from rest_framework.authtoken import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tasks.urls')),
    path('accounts/',include('accounts.urls')),
    path('api/v1/',include(router.urls),name="api"),
    path('api-token-auth',views.obtain_auth_token,name="api-token"),
]


urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tasks/models.py
from django.db import models
from accounts.models import UserProfile
from django.utils import timezone

# Create your models here.

"""
Task model class will keep user's task with title, status, description, and due date.
"""
class Task(models.Model):
    # status feilds choices
    STATUS = (
        ('Draft', 'Draft'),
        ('Started', 'Started'),
        ('Pending', 'Pending'),
        ('Finished', 'Finished')
    )
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, default=None)
    title = models.CharField(max_length=255)
    status = models.CharField(max_length=10, choices=STATUS)
    description = models.TextField()
    due_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    # calculate time remaining to due date.
    def calculate_time(self):
        now = timezone.now()
        time = self.due_date - now
        days = time.days
        seconds = time.seconds
        hours = seconds//3600

        return str(days) + " days, " + str(hours) + " hours"

    # return part text of description
    def descriptionSnipp(self):
        return self.description[:15] + ' ...'

tasks/forms.py
from django import forms
from .models import Task

"""
Model form for creating task
all fileds in form exclude user
"""
class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'
        exclude = ['user']

tasks/views.py
from django.shortcuts import render,redirect
from django.views import View
from .models import Task
from accounts.models import UserProfile
from .forms import CreateTaskForm

# Create your views here.

"""
This is index page and show list of user's tasks and all other tasks.
We sure that user should login to access to this page. user can view, update and delete own task
with button in each row
"""
class TaskList(View):
    template_name = 'tasks/index.html'
    def get(self,request):
        login_user = UserProfile.objects.get(user=request.user) # get login user

        allTask = Task.objects.exclude(user_id=request.user.id) # read all task exclude login user task
        myTask = Task.objects.filter(user_id=request.user.id)   # read user's tasks
        taskStarted = myTask.filter(status='Started').count()   # count user's task with started status
        taskPending = myTask.filter(status='Pending').count()   # count user's task with pending status
        taskFinished = myTask.filter(status='Finished').count() # count user's task with finished status

        # make context for render HTML template
        context = {
            'login_user':login_user,
            'task_started':taskStarted,
            'task_pending':taskPending,
            'task_finished':taskFinished,
            'all_task':allTask,
            'my_task':myTask
        }
        return render(request,self.template_name,context)

"""
This is user's task page for showing only user's task. user can view, update and delete tasks
"""
class MyTask(View):
    template_name = 'tasks/my_task.html'

    def get(self,request):
        login_user = UserProfile.objects.get(user=request.user) # get login user
        myTask = Task.objects.filter(user_id=request.user.id)   # read user's tasks
        
        # make context for render HTML template
        context = {
            'login_user':login_user,
            'my_task':myTask,
        }
        return render(request,self.template_name, context)

"""
This is all task page for showing all other task. user just can view other tasks
"""
class AllTask(View):
    template_name = 'tasks/all_task.html'
    def get(self,request):
        login_user = UserProfile.objects.get(user=request.user) # get login user
        allTask = Task.objects.exclude(user_id=request.user.id) # read user's tasks

        # make context for render HTML template
        context = {
            'login_user':login_user,
            'all_task':allTask
        }

        return render(request,self.template_name,context)

"""
This view is about create task. use form model for creating task
"""
class CreateTask(View):
    template_name = 'tasks/create_task.html'
    def get(self,request,id):
        login_user = UserProfile.objects.get(user=request.user) # get login user
        form = CreateTaskForm(instance=login_user)

        # make context for render HTML template
        context = {
            'form':form
        }
        return render(request,self.template_name,context)

    def post(self,request,id):
        login_user = UserProfile.objects.get(user=request.user) # get login user
        form = CreateTaskForm(request.POST)
        # check form is valid or not
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = login_user
            instance.save()
            return redirect('/')

"""
This view is about update task.
"""
class UpdateTask(View):
    template_name = 'tasks/create_task.html'

    def get(self,request,id):
        task = Task.objects.get(id=id)
        form = CreateTaskForm(instance=task)
        context = {
            'form':form
        }
        return render(request,self.template_name,context)

    def post(self,request,id):
        task = Task.objects.get(id=id)
        form = CreateTaskForm(request.POST,instance=task)

        if(form.is_valid()):
            form.save()
            return redirect('/')

"""
This view is about delete task.
"""
class DeleteTask(View):
    template_name = 'tasks/delete_task.html'

    def get(self,request,id):
        task = Task.objects.get(id=id)
        context={
            'task':task
        }
        return render(request,self.template_name,context)

    def post(self,request,id):
        task = Task.objects.get(id=id)
        task.delete()
        return redirect('/')

"""
This view is about view task.
"""
class ViewTask(View):
    template_name = 'tasks/view_task.html'

    def get(self,request,id):
        login_user = UserProfile.objects.get(user=request.user)
        task = Task.objects.get(id=id)
        context = {
            'login_user':login_user,
            'task':task
        }
        return render(request,self.template_name,context)

tasks/templates/tasks/all_task.html
{% extends 'base.html' %}
{% block title %}
All Task
{% endblock title %}
{% block content %}
{% include 'navbar.html' %}
<br>

<div class="row">
  <div class="col-md">
    <div class="card card-body">
      <h5>All Task</h5>
    </div>
    <br>
    <div class="card card-body">
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th>Title</th>
            <th>Status</th>
            <th>Created By</th>
            <th>Description</th>
            <th>Due Date</th>
            <th>Remaining</th>
            <th>View</th>
          </tr>
        </thead>
        <tbody>
          {% for task in all_task %}
          <tr>
            <td>{{task.title}}</td>
            <td>{{task.status}}</td>
            <td>{{task.user.user.username}}</td>
            <td>{{task.descriptionSnipp}}</td>
            <td>{{task.due_date}}</td>
            <td>{{task.calculate_time}}</td>
            <td><a class="btn btn-sm btn-info" href="{% url 'tasks:view_task' task.id %}">View</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

</div>

{% endblock content %}

tasks/templates/tasks/create_task.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
New Task
{% endblock title %}
{% block content %}
{% load crispy_forms_tags %}
<br>
<div class="row d-flex justify-content-center">
  <div class="col-md-6">
    <div class="card card-body">
      <form action="" method="POST">
        {% csrf_token %}

        {{form|crispy}}

        <input class="btn btn-success" type="submit" name="Submit">
        <a class="btn btn-outline-danger" href="/">Cancel</a>
      </form>
    </div>
    <br>
  </div>
</div>
{% endblock %}

tasks/templates/tasks/delete_task.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<div class="row d-flex justify-content-center">
  <div class="col-md-6">
    <div class="card card-body">
      <p>Are you sure you want to delete "{{task.title}}"?</p>
      <form class="" action="{% url 'tasks:delete_task' task.id %}" method="POST">
        {% csrf_token %}
        <a class="btn btn-outline-warning" href="{% url 'tasks:task_list' %}">Cancel</a>
        <input class="btn btn-danger" type="submit" name="Confirm">
      </form>
    </div>

  </div>

</div>

{% endblock %}

tasks/templates/tasks/index.html
{% extends 'base.html' %}
{% block title %}
Dashboard
{% endblock title %}
{% block content %}
    {% include 'navbar.html'%}
    {% include 'tasks/status.html' %}
<div class="row container-fluid">
  <div class="col-md-7">
    <h5>My Task</h5>
    <hr>
    <div class="card card-body">
      <a class="btn btn-outline-primary btn-sm btn-block" href="{% url 'tasks:create_task' user.id %}">Create Task</a><br>
      <table class="table table-sm">
        <tr>
          <th>Title</th>
          <th>Status</th>
          <th>Remaining</th>
          <th>View</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>

        {% for mytask in my_task %}
        <tr>
            <td>{{mytask.title}}</td>
            <td>{{mytask.status}}</td>
            <td>{{mytask.calculate_time}}
            <td><a class="btn btn-sm btn-outline-info" href="{% url 'tasks:view_task' mytask.id %}">View</a></td>
            <td><a class="btn btn-sm btn-outline-success" href="{% url 'tasks:update_task' mytask.id %}">Update</a></td>
            <td><a class="btn btn-sm btn-outline-danger" href="{% url 'tasks:delete_task' mytask.id %}">Delete</a></td>
        </tr>
        {% endfor %}

      </table>
    </div>
  </div>

  <div class="col-md-5">
    <h5>All Task</h5>
    <hr>
    <div class="card card-body">
      <table class="table table-sm">
        <tr>
          <th>Title</th>
          <th>Status</th>
          <th>Created By</th>
          <th>View</th>
        </tr>

        {% for task in all_task %}
        <tr>
          <td>{{task.title}}</td>
          <td>{{task.status}}</td>
          <td>{{task.user.user.username}}</td>
          <td><a class="btn btn-sm btn-info" href="{% url 'tasks:view_task' task.id %}">View</a></td>
        </tr>
        {% endfor %}

      </table>
    </div>
    <br>
  </div>
</div>
{% endblock content %}

tasks/templates/tasks/my_task.html
{% extends 'base.html' %}
{% block title %}
My Task
{% endblock title %}
{% block content %}
{% include 'navbar.html' %}
<br>

<div class="row">
  <div class="col-md">
    <div class="card card-body">
      <h5>{{login_user.firstname.capitalize}}'s Tasks</h5>
    </div>
    <br>
    <div class="card card-body">
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th>Title</th>
            <th>Status</th>
            <th>Description</th>
            <th>Due Date</th>
            <th>Remaining</th>
            <th>View</th>
            <th>Update</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for task in my_task %}
          <tr>
            <td>{{task.title}}</td>
            <td>{{task.status}}</td>
            <td>{{task.descriptionSnipp}}</td>
            <td>{{task.due_date}}</td>
            <td>{{task.calculate_time}}</td>
            <td><a class="btn btn-sm btn-outline-info" href="{% url 'tasks:view_task' task.id %}">View</a></td>
            <td><a class="btn btn-sm btn-outline-success" href="{% url 'tasks:update_task' task.id %}">Update</a></td>
            <td><a class="btn btn-sm btn-outline-danger" href="{% url 'tasks:delete_task' task.id %}">Delete</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

</div>

{% endblock content %}

tasks/templates/tasks/status.html
<br>

<div class="row container-fluid">
  <div class="col">
    <div class="col-md">
      <div class="card text-center text-white  mb-3" id="task-started">
        <div class="card-header">
          <h5 class="card-title">Started</h5>
        </div>
        <div class="card-body">
          <h3 class="card-title">{{task_started}}</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="col">
    <div class="col-md">
      <div class="card text-center text-white  mb-3" id="task-pending">
        <div class="card-header">
          <h5 class="card-title">Pending</h5>
        </div>
        <div class="card-body">
          <h3 class="card-title">{{task_pending}}</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="col">
    <div class="col-md">
      <div class="card text-center text-white  mb-3" id="task-finished">
        <div class="card-header">
          <h5 class="card-title">Finished</h5>
        </div>
        <div class="card-body">
          <h3 class="card-title">{{task_finished}}</h3>
        </div>
      </div>
    </div>
  </div>
</div>

tasks/templates/tasks/view_task.html
{% extends 'base.html' %}
{% block title %}
Task Detail
{% endblock title %}
{% block content %}
{% include 'navbar.html' %}
<br>
<div class="container">
  <div class="row">
    <div class="col-md-3 text-center">
      <div class="card card-body">
        <a class="btn btn-warning" href="/"> &#8592; Back to Dashbaord</a>
        <br>
        <h3 class="display-4 text-info">{{task.status}}</h3>
       </div>
    </div>
    <br/>
    <div class="col-md-9">
      <div class="card card-body">
        <table class="table">
          <tbody>
            <tr>
              <th>Title</th>
              <td>{{task.title}}</td>
            </tr>
            <tr>
              <th>Description</th>
              <td>{{task.description}}</td>
            </tr>
            <tr>
              <th>Due Date</th>
              <td>{{task.due_date}} , {{task.calculate_time}}</td>
            </tr>
            <tr>
              <th>Created By</th>
              <td>{{task.user.user.username}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <br>
</div>
{% endblock content %}